### ISSUE TITLE
NullPointerException when turning database off

### ISSUE THREAD

**Issue by kronrod** [jasmineRepo/JAS-mine-core#2]
When enabling the option "Turn database off" and then clicking the "Build simulation model" button, a NullPointerException is happens and the GUI becomes unresponsive. The Stacktrace is attached below. You can reproduce this by installing eclipse, installing the Jasmine plugin, creating a Jasmine project and then running it.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at microsim.data.db.DatabaseUtils.loadTable(DatabaseUtils.java:388)
at microsim.data.db.DatabaseUtils.loadTable(DatabaseUtils.java:384)
at test.model.TestModelModel.buildObjects(TestModelModel.java:36)
at microsim.engine.SimulationEngine.buildModels(SimulationEngine.java:405)
at microsim.gui.shell.MicrosimShell$SimulationController.buildModel(MicrosimShell.java:627)
at microsim.gui.shell.MicrosimShell$3.actionPerformed(MicrosimShell.java:354)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
at java.awt.Component.processMouseEvent(Component.java:6535)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6300)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by rer98** [comment]
Dear Luzius,

Thank you very much for pointing this issue out to me.  I have now fixed the problem: there was a bug in the template of a JAS-mine project in the JAS-mine Plugin for Eclipse IDE, and also another bug in the underlying JAS-mine core libraries that was related to the issue you reported.

Please could you update the JAS-mine Plugin for Eclipse IDE (to version 3.2.1), by following section 3 on the same webpage, http://www.jas-mine.net/home/documentation/tutorials/how-to-update-jasmine). This will ensure that whenever you use the plugin to create a new JAS-mine project in future, you will have the debugged templates and also version 3.2.1 of the JAS-mine-core and JAS-mine-gui dependencies will be used by default.

Also, if you have any existing code that uses the JAS-mine libraries, please update to the latest version of JAS-mine: version 3.2.1 You can do this simply by changing the versions of both JAS-mine-core and JAS-mine-gui dependencies in your project's pom.xml to 3.2.1 (please see the detailed instructions of section 1 in http://www.jas-mine.net/home/documentation/tutorials/how-to-update-jasmine).

In addition to solving the bug you highlighted, you will probably notice that we have made the decision to remove the 'Turn off database' button on the Microsim shell (the JAS-mine GUI).  This design choice was made because we felt that there was not so much to gain from offering this option on the GUI but a lot of potential dangers for the inexperienced JAS-mine user.  

The original rationale for offering the 'Turn off database' button (formerly known as 'Silent mode' in older versions of JAS2 / JAS-mine) was to allow the user to shorten the time it took to build and execute a simulation by not establishing a connection to the database if such a connection was not necessary for a project.  This would remove the database functionality of the JAS-mine project altogether, with the only way to export data (from the JAS-mine classes) being via CSV files.  However, the drawbacks of doing this are that any subsequent attempt to export to an output database would silently fail and, moreover, any simulation that requires data from an input database in order to run would throw an exception similar to the one you reported.

Because of these potential drawbacks, we deemed it safer to remove the 'Turn off database' option altogether and always automatically establish the database connection; in reality, it takes very little time and memory to establish the database connection during the build phase, and the user can already choose to export output data to CSV files instead of the output database using the GUI parameters of the JAS-mine project's Observer class anyway (these options are automatically available in the template project of the JAS-mine Plugin for Eclipse IDE).

We still offer the user the explicit option of turning off the database connection (equivalent to ticking the 'Turn off database' box in the GUI), however this must now be done programmatically on line 23 of the Start class of the JAS-mine project, by setting the Simulation Engine's setTurnOffDatabaseConnection to true.  There is also a warning in Java comments above line 23 describing the possible issues of doing so.

I do hope you agree with our new design choice, and please let me know if you have any concerns or further issues with JAS-mine.

Many thanks for your patience and best wishes,

Ross

**Comment by kronrod** [comment]
Thanks for fixing this so quickly!
